//T03_UsrEcption를 테스트하는 메인.
import java.io.IOException;
public class T03_UsrEcptionEX2{

	/*	public static void main(String[] args) {
		System.out.println("시작");
		try{
			method();
		}catch(Exception ex){
			System.out.println("");
		}
		System.out.println("끝");
	}
	//여기까진 메인함수

	/* 이 아래부터 Db에 연결하는 코딩이라 하자
	 * trycatch일 경우 여기서 예외가 발생했다 하더라도 메인함수에서 정상이라고 판단하고 있다.
	 * 이러면 안됨.
	 */
	/*	static void method(){//예외발생 시
		System.out.println("네트작업을 하는 부분");
		throw new T03_UsrEcption();
	}
} */